### ISSUE TITLE
Cannot read property 'BlazeLayout' of undefined after package update

### ISSUE THREAD

**Issue by derwaldgeist** [kadirahq/blaze-layout#56]
In my Meteor 1.1 app, I executed a ```meteor update --packages-only``` and got this update report:

```
babrahams:editable-json    removed from your project
cfs:storage-adapter        upgraded from 0.2.1 to 0.2.3
cfs:tempstore              upgraded from 0.1.4 to 0.1.5
gwendall:session-json      removed from your project
kadira:blaze-layout        upgraded from 2.1.0 to 2.2.0
kadira:debug               upgraded from 2.2.3 to 2.2.4
kadira:flow-router         upgraded from 2.6.2 to 2.8.0
meteorhacks:kadira         upgraded from 2.23.4 to 2.25.0
meteorhacks:meteorx        upgraded from 1.3.1 to 1.4.1
meteorhacks:search-source  upgraded from 1.4.0 to 1.4.1
meteortoys:toykit*         upgraded from 0.8.7 to 1.0.4
msavin:jetsetter           upgraded from 1.0.20 to 1.1.0
msavin:mongol              upgraded from 1.1.5 to 1.2.0
semantic:ui                upgraded from 2.1.4 to 2.1.4_3
semantic:ui-data           upgraded from 2.1.4 to 2.1.5
```

After this upgrade, the app won't start anymore and throws the following exception:
```bash
W20151104-11:02:44.175(1)? (STDERR) /Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151104-11:02:44.175(1)? (STDERR) 						throw(ex);
W20151104-11:02:44.175(1)? (STDERR) 						      ^
W20151104-11:02:44.179(1)? (STDERR) TypeError: Cannot read property 'BlazeLayout' of undefined
W20151104-11:02:44.179(1)? (STDERR)     at /Users/waldgeist/Documents/Development/htdocs/aiddogs/webapp/.meteor/local/build/programs/server/packages/useraccounts_flow-routing.js:7:49
W20151104-11:02:44.179(1)? (STDERR)     at /Users/waldgeist/Documents/Development/htdocs/aiddogs/webapp/.meteor/local/build/programs/server/packages/useraccounts_flow-routing.js:264:3
W20151104-11:02:44.179(1)? (STDERR)     at /Users/waldgeist/Documents/Development/htdocs/aiddogs/webapp/.meteor/local/build/programs/server/boot.js:222:10
W20151104-11:02:44.179(1)? (STDERR)     at Array.forEach (native)
W20151104-11:02:44.179(1)? (STDERR)     at Function._.each._.forEach (/Users/waldgeist/.meteor/packages/meteor-tool/.1.1.4.17074nh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151104-11:02:44.179(1)? (STDERR)     at /Users/waldgeist/Documents/Development/htdocs/aiddogs/webapp/.meteor/local/build/programs/server/boot.js:117:5
```
The problem occurs in the ```useraccounts-flow-routing``` package. But as this packages has not been upgraded, I think that the ```blazelayout``` package might be the root cause.

**Comment by arunoda** [comment]
Not sure what going on. May be call `meteor reset` and run your app again. Also, try to check that useraccouts package.

**Comment by reustle** [comment]
I'm not using `useraccounts-flow-routing` but also getting this error. I also tried resetting the db with `meteor reset`. Why was the issue closed right away?

**Comment by KristerV** [comment]
hmm, now I'm gettings this.. not good :)
ah, updating to Meteor 1.2 fixed it.

**Comment by avalanche1** [comment]
I solved that by removing blaze-layout from app and then cloning it from git into 'packages' folder of my proj

**Comment by bhaveshvavdiya** [comment]
Yes, It is working after removing blaze-layout.
Thanks @avalanche1
